export enum Industry {
  IT = 'IT',
  Education = 'Education',
  Finance = 'Finance',
  Health = 'Health',
  Marketing = 'Marketing',
  Retail = 'Retail',
  Manufacturing = 'Manufacturing',
  Hospitality = 'Hospitality',
  Construction = 'Construction',
  Consulting = 'Consulting',
  Telecommunications = 'Telecommunications',
  MediaAndEntertainment = 'Media and Entertainment',
  TransportationAndLogistics = 'Transportation and Logistics',
  Nonprofit = 'Nonprofit',
  Government = 'Government',
  LegalServices = 'Legal Services',
  Sales = 'Sales',
}
